spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: orderDb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
management:
  tracing:
    sampling:
      probability: 1.0