spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${ENV_DB_URL}
    username: ${ENV_DB_USERNAME}
    password: ${ENV_DB_PASSWORD}
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
management:
  tracing:
    sampling:
      probability: 1.0
